### ISSUE TITLE
Error when exporting checkpoint: 'Namespace' has no 'residual_level'

### ISSUE THREAD

**Issue by HaraldKorneliussen** [pytorch/translate#60]
I used the docker image to train a model, but when I tried to export it I got this error message:

```
Ignoring @/caffe2/caffe2/contrib/aten:aten_op as it is not a valid file.
Traceback (most recent call last):
  File "pytorch_translate/onnx_component_export.py", line 124, in <module>
    main()
  File "pytorch_translate/onnx_component_export.py", line 86, in main
    dst_dict_filename=args.dst_dict,
  File "/home/translate/pytorch_translate/ensemble_export.py", line 236, in build_from_checkpoints
    dst_dict_filename,
  File "/home/translate/pytorch_translate/ensemble_export.py", line 62, in load_models_from_checkpoints
    dst_dict,
  File "/home/translate/pytorch_translate/rnn.py", line 218, in build_model
    residual_level=args.residual_level,
AttributeError: 'Namespace' object has no attribute 'residual_level'
```

I also got this error message previously when I tried to export checkpoints from models I'd trained with fairseq-py - I assumed it just meant this wasn't supported, but since it happens on models trained with this project as well it's maybe a bug.

The command I used to export was:

```
#!/bin/bash

export NCCL_ROOT_DIR="$(pwd)/nccl_2.1.15-1+cuda8.0_x86_64"
export LD_LIBRARY_PATH="${NCCL_ROOT_DIR}/lib:${LD_LIBRARY_PATH}"
python3 pytorch_translate/onnx_component_export.py \
    --checkpoint mounted/checkpoints/checkpoint_best.pt \
    --encoder_output_file mounted/export/encoder.pb \
    --decoder_output_file mounted/export/decoder.pb \
    --src_dict mounted/checkpoints/dictionary-in.txt \
    --dst_dict mounted/checkpoints/dictionary-out.txt \
    --beam_size 6 \
    --word_penalty 0.25 \
    --unk_penalty -0.5 \
    --batched_beam && \
  echo "Finished exporting encoder as ./encoder.pb and decoder as ./decoder.pb"
```

The command I used to train this model was:

```
#!/bin/bash

export NCCL_ROOT_DIR="$(pwd)/nccl_2.1.15-1+cuda8.0_x86_64"
export LD_LIBRARY_PATH="${NCCL_ROOT_DIR}/lib:${LD_LIBRARY_PATH}"
CUDA_VISIBLE_DEVICES=0 python3 pytorch_translate/train.py \
   "" \
   --arch fconv_iwslt_de_en \
   --lr-scheduler reduce_lr_on_plateau \
   --lr-shrink 0.1 \
   --max-epoch 20 \
   --optimizer nag \
   --lr 0.3 \
   --clip-norm 0.1 \
   --criterion cross_entropy \
   --batch-size 256 \
   --max-tokens 3000 \
   --save-dir /home/translate/mounted/checkpoints \
   --beam 5 \
   --source-lang in \
   --target-lang out \
   --source-vocab-file /home/translate/mounted/checkpoints/dictionary-in.txt \
   --target-vocab-file /home/translate/mounted/checkpoints/dictionary-out.txt \
   --train-source-text-file /home/translate/mounted/bpe/train.in \
   --train-target-text-file /home/translate/mounted/bpe/train.out \
   --eval-source-text-file /home/translate/mounted/bpe/valid.in \
   --eval-target-text-file /home/translate/mounted/bpe/valid.out \
   --log-interval 1000 \
   2>&1 | tee -a /home/translate/mounted/checkpoints/log

```

I notice the error is in rnn.py, but I don't use an rnn, but an fconv model. Are these models not yet supported for export?

**Comment by HaraldKorneliussen** [comment]
OK, training RNN model then!
