### ISSUE TITLE
ONNX export of RNN failed, Cannot export individual pack_padded_sequence/pad_packed_sequence

### ISSUE THREAD

**Issue by HaraldKorneliussen** [pytorch/translate#61]
The new RNN model I trained didn't export properly, I got this error message:

```
Ignoring @/caffe2/caffe2/contrib/aten:aten_op as it is not a valid file.
Traceback (most recent call last):
  File "pytorch_translate/onnx_component_export.py", line 124, in <module>
    main()
  File "pytorch_translate/onnx_component_export.py", line 89, in main
    encoder_ensemble.save_to_db(args.encoder_output_file)
  File "/home/translate/pytorch_translate/ensemble_export.py", line 213, in save_to_db
    self.onnx_export(tmp_file)
  File "/home/translate/pytorch_translate/ensemble_export.py", line 204, in onnx_export
    output_names=self.output_names,
  File "/home/translate/pytorch_translate/ensemble_export.py", line 44, in onnx_export_ensemble
    output_names=output_names,
  File "/home/miniconda/lib/python3.6/site-packages/torch/onnx/__init__.py", line 20, in _export
    return utils._export(*args, **kwargs)
  File "/home/miniconda/lib/python3.6/site-packages/torch/onnx/utils.py", line 207, in _export
    proto, export_map = graph.export(params, _onnx_opset_version, defer_weight_export, export_raw_ir)
RuntimeError: ONNX export failed: Cannot export individual pack_padded_sequence or pad_packed_sequence; these operations must occur in pairs.

```
... followed by a long stacktrace.

The model was trained with this command line/script, based on the example:

```
#!/bin/bash

export NCCL_ROOT_DIR="$(pwd)/nccl_2.1.15-1+cuda8.0_x86_64"
export LD_LIBRARY_PATH="${NCCL_ROOT_DIR}/lib:${LD_LIBRARY_PATH}"
CUDA_VISIBLE_DEVICES=0 python3 pytorch_translate/train.py \
   "" \
   --arch rnn \
   --lr-scheduler fixed \
   --force-anneal 200 \
   --max-epoch 100 \
   --stop-time-hr 72 \
   --optimizer sgd \
   --lr 0.5 \
   --clip-norm 5.0 \
   --criterion label_smoothed_cross_entropy \
   --batch-size 256 \
   --lenpen 0 \
   --unkpen 0.5 \
   --word-reward 0.25 \
   --max-tokens 3000 \
   --encoder-layers 2 \
   --encoder-embed-dim 256 \
   --encoder-hidden-dim 512 \
   --decoder-layers 2 \
   --decoder-embed-dim 256 \
   --decoder-hidden-dim 512 \
   --decoder-out-embed-dim 256 \
   --save-dir /home/translate/mounted/checkpoints \
   --attention-type dot \
   --sentence-avg \
   --momentum 0 \
   --generate-bleu-eval-avg-checkpoints 10 \
   --generate-bleu-eval-per-epoch \
   --beam 6 \
   --no-beamable-mm \
   --source-lang in \
   --target-lang out \
   --source-vocab-file /home/translate/mounted/checkpoints/dictionary-in.txt \
   --target-vocab-file /home/translate/mounted/checkpoints/dictionary-out.txt \
   --train-source-text-file /home/translate/mounted/bpe/train.in \
   --train-target-text-file /home/translate/mounted/bpe/train.out \
   --eval-source-text-file /home/translate/mounted/bpe/valid.in \
   --eval-target-text-file /home/translate/mounted/bpe/valid.out \
   --source-max-vocab-size 14000 \
   --target-max-vocab-size 14000 \
   --log-interval 500 \
   2>&1 | tee -a /home/translate/mounted/checkpoints/log

```

(I see now that I forgot to make it an LSTM, wow. How did I even get good results?)

The export command was exactly the same as the example, only the path being different and the download being removed. I tried exporting many different checkpoints, averaged and not.

**Comment by jmp84** [comment]
cc @jamesr66a 
@HaraldKorneliussen , we're working on extending ONNX export support to more models. Could you try adding the options `--cell-type lstm` and `--sequence-lstm`. Currently, we can only guarantee that the export will work with `torch.nn.LSTM` but not with custom cells.

**Comment by HaraldKorneliussen** [comment]
I did just that, and stopped training after one epoch just to be sure the export would work this time. It did!
